<?php
//TODO: sanitize_key() <- Add this
//Useful link
//https://stackoverflow.com/questions/41362277/wp-rest-api-custom-end-point-post-request
//https://stackoverflow.com/questions/44189832/wordpress-rest-api-custom-endpoint-for-method-post
/*------------------GETs---------------------------*/
function get_all_grabbings() {
    // Returns all grabbings in the database
    global $wpdb;
    $query = "SELECT * FROM inku_kaehmy_grabbing;";
    $grabbings = $wpdb->get_results($query, ARRAY_A);
    return $grabbings;
}

function get_grabbing($request) {
    // Param ID returns grabbing with given ID
    $grabbing_ID = (int)$request['id'];
    global $wpdb;
    $query = $wpdb->prepare(
        "SELECT * 
        FROM inku_kaehmy_grabbing
        WHERE ID=%d;",
        $grabbing_ID
    );
    $grabbing = $wpdb->get_row($query);
    return $grabbing;
}

function get_all_tags() {
    global $wpdb;
    $query = "SELECT * FROM inku_kaehmy_tag;";
    $res = $wpdb->get_results($query, ARRAY_A);
    if($res){
        return $res;
    }
    else{
        return http_response_code(404);
    }
}

function get_grabbing_comments($request){
    global $wpdb;

    $grabbing_ID = (int)$request['id'];

    $query = $wpdb->prepare(
        "SELECT * FROM inku_kaehmy_comment WHERE ID IN 
        (SELECT comment_ID FROM inku_kaehmy_has_comment WHERE parent_grabbing_ID = %d)
        ", $grabbing_ID);


    $res = $wpdb->get_results($query, ARRAY_A);

    if($res){
        return $res;
    }
    else{
        return http_response_code(404);
    }
}

/*---------------------DELETEs----------------------*/ 
function delete_comment($request) {

    $nonce = $request['_wpnonce'];

    if(! wp_verify_nonce($nonce, 'delete_comment')){
        return http_response_code(418);
    }
    $comment_id = $request['id'];
    if(is__user_logged_in()){
        global $wpdb;
        $query = $wpdb->prepare(
            "DELETE
            FROM inku_kaehmy_comment
            WHERE ID=%d;",
            $comment_id
        );
        $wpdb->query($query);
        return http_response_code(200);
    }
}

function delete_grabbing($request) {

    $nonce = $request['_wpnonce'];

    if(! wp_verify_nonce($nonce, 'delete_comment')){
        return http_response_code(418);
    }

    if(is__user_logged_in()){
        global $wpdb;
        $query = $wpdb->prepare(
            "DELETE
            FROM inku_kaehmy_grabbing
            WHERE ID=%d;",
            $grabbing_ID
        );
        $wpdb->query($query);
        return http_response_code(200);
    }
}
/*--------------POSTs----------------------*/ 
/*TODO: Add these to post. Must be generated by quesry.    
//$userID = get_user_id();
    //$ID = something()*/
function post_grabbing($request){
    $nonce = $request['_wpnonce'];

    if(! wp_verify_nonce($nonce, 'post_grabbing')){
        exit;
    }

    if(is__user_logged_in()){
        $is_hallitus = $request['gov'];
        $grabbing_text = $request['text'];
        $grabbing_title = $request['title'];
        $grabbing_patch = $request['patch'];
        global $wpdb;
        // $query = $wpdb->prepare(
        //     "QUERY"
        // );
        // $wpdb->query($query);
        return http_response_code(501);
    }
    return http_response_code(501);
}

function post_comment($requet)
{
    $nonce = $request['_wpnonce'];

    if(! wp_verify_nonce($nonce, 'post_grabbing')){
        exit;
    }

    if(is__user_logged_in()){
        $comment_text = $request['text'];
        $comment_title = $request['title'];
        $parent_id = $request['parent-id'];
        global $wpdb;
        // $query = $wpdb->prepare(
        //     "QUERY"
        // );
        // $wpdb->query($query);
        return http_response_code(501);
    }
    return http_response_code(501);
}

/*-------------------------PUTs-----------------------*/
function put_comment($request) {

    $nonce = $request['_wpnonce'];

    if(! wp_verify_nonce($nonce, 'delete_comment')){
        exit;
    }
    $comment_id = $request['id'];
    if(is__user_logged_in()){
        $comment_text = $request['text'];
        $comment_title = $request['title'];
        $parent_id = $request['parent-id'];
        global $wpdb;
        // $query = $wpdb->prepare(

        // );
        // $wpdb->query($query);
        return http_response_code(501);
    }
}

/*-------------------------PUTs-----------------------*/
function put_grabbing($request) {

    $nonce = $request['_wpnonce'];

    if(! wp_verify_nonce($nonce, 'delete_comment')){
        exit;
    }
    $comment_id = $request['id'];
    if(is__user_logged_in()){
        $grabbing_text = $request['text'];
        $grabbing_title = $request['title'];
        $grabbing_patch = $request['patch'];
        global $wpdb;

        // $query = $wpdb->prepare(

        // );
        // $wpdb->query($query);
        return http_response_code(501);
    }
}


function test() {
    return get_all_tags();
}


?>